### PR TITLE
Create base application

### LINKED ISSUE #5: Create backend application's base

### PR DESCRIPTION
**Pull request by vestacic**
Created the base of MVC application

### CODE REVIEW

**Review by arminasbrazenas — CHANGES_REQUESTED** [review]
We don't need html/css/bootstrap files since we already started creating a frontend in React. I believe we are supposed to create a project with ASP.NET Core Web API template, which contains only the backend stuff (controllers).

**Comment by vestacic** [comment]
> We don't need html/css/bootstrap files since we already started creating a frontend in React. I believe we are supposed to create a project with ASP.NET Core Web API template, which contains only the backend stuff (controllers).

fixed

**Review by AkvileR — APPROVED** [review]
I think everything looks good now

**Review by arminasbrazenas — APPROVED** [review]
Looks good

**Pull request merged**
